In [8]:
import numpy as np
import scipy.special

In [33]:
ex1 = np.random.rand(3, 3) -0.5 

In [34]:
ex1

array([[ 0.21617572,  0.3541205 , -0.48623006],
       [ 0.11831759, -0.07600265, -0.3410743 ],
       [-0.23562025, -0.23836402, -0.4209313 ]])

In [37]:
ex2 = np.array([[100], [1000], [10000]])

In [38]:
ex1 * ex2

array([[   21.61757158,    35.41205001,   -48.62300574],
       [  118.31758775,   -76.002646  ,  -341.07430237],
       [-2356.20249351, -2383.64018469, -4209.31302949]])

In [32]:
class neuralNetwork:
    
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # of nods
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        #3x3크기이고, 책에서 나왔던 good initialization method가 쓰인 것
        self.wih = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        
        self.who = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))
        
        #activaition function 
        self.activaion_function = lambda x: scipy.special.expit(x)
        
        # learning rate
        self.lr = learningrate
        pass
    
    def train(self, inputs_list, targets_list):
        inputs = np.array(inputs_list, ndim=2).T
        targets= np.array(targets_list, ndim=2).T
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs =self.activaion_function(hidden_inputs)
        
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.activaion_function(final_inputs)
        
        output_errors = targets - final_outputs
        #Back Propagation
        hidden_errors = np.dot(self.who.T, output_errors)
        self.who += self.lr*np.dot((output_errors*final_outputs*(1.0-final_outputs)), np.transpose(hidden_outputs))
        self.wih += self.lr*np.dot((hidden_errors*hidden_outputs*(1.0-hidden_outputs)), np.transpose(inputs))
        
        
        pass
    
    def query(self, input_list):
        inputs = np.array(input_list, ndmin=2).T
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs =self.activaion_function(hidden_inputs)
        
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.activaion_function(final_inputs)
        
        return final_outputs
        
        pass

In [23]:
input_nodes = 3
hidden_nodes = 3
output_nodes = 3
learning_rate = 0.3

In [30]:
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

In [31]:
n.query([1.0, 0.5, -1.5])

array([[0.4489073 ],
       [0.52206434],
       [0.4617674 ]])

In [9]:
inputs = [1,2,3,4,5,6]

In [19]:
input_list = np.array(inputs, ndmin=2).T

In [20]:
input_list

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])