In [2]:
import tensorflow as tf

In [3]:
x = tf.Variable(3, name="x")
y = tf.Variable(3, name="y")

In [4]:
f = x*x*y + y + 2

In [5]:
f

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [6]:
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)

In [7]:
print(result)

32


In [8]:
sess.close()

In [9]:
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()

In [10]:
result

32

In [13]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    result = f.eval()

In [14]:
result

32

In [17]:
init = tf.global_variables_initializer()
sess = tf.InteractiveSession()
init.run()
result = f.eval()
print(result)

32


In [18]:
sess.close()

#### 계산 그래프 관리

In [19]:
x1 = tf.Variable(1)

In [21]:
x1.graph is tf.get_default_graph()

True

In [23]:
graph = tf.Graph()

In [24]:
graph

In [25]:
with graph.as_default():
    x2 = tf.Variable(2)

In [26]:
x2.graph is graph

True

In [27]:
x2.graph is tf.get_default_graph()

False

### 노드 값의 생애주기

In [28]:
w = tf.constant(3)
x = w+2
y = x+5
z = x*3

In [31]:
with tf.Session() as sess:
    print(y.eval())
    print(z.eval())

10
15


In [38]:
with tf.Session() as sess:
    y_val2 = y.eval()
    y_val, z_val = sess.run([y, z])
    print(y_val2)
    print(y_val)
    print(z_val)

10
10
15


### Linear Algebra with Tensorflow

In [39]:
import numpy as np
from sklearn.datasets import fetch_california_housing

In [41]:
housing = fetch_california_housing()

In [42]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': 'California housing dataset.\n\nThe original database is available from StatLib\n\n 

In [46]:
m, n = housing.data.shape

In [50]:
np.ones((m, 1))

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [51]:
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

In [52]:
housing_data_plus_bias

array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

In [54]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")

In [56]:
XT = tf.transpose(X)

In [57]:
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

In [59]:
with tf.Session() as sess:
    theta_val = theta.eval()
    print(theta)

Tensor("MatMul_2:0", shape=(9, 1), dtype=float32)


### Gradient Descent instead Normal Equation

In [60]:
n_epochs = 1000;
learning_rate = 0.01

In [62]:
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")

NameError: name 'scaled_housing_data_plus_bias' is not defined

### Data Input

In [64]:
A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5

In [67]:
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6], [7, 8, 9]]})

In [68]:
print(B_val_1)

[[6. 7. 8.]]


In [69]:
print(B_val_2)

[[ 9. 10. 11.]
 [12. 13. 14.]]


### Visualization with TensorBoard

In [70]:
from datetime import datetime

In [72]:
now = datetime.utcnow().strftime("%Y%m%d%H%M%S")

In [74]:
root_logdir = "tf_logs"

In [76]:
logdir = "{}/run-{}/".format(root_logdir, now)

'tf_logs/run-20180902070306/'