In [1]:
import numpy as np

## ndarray
ndarray는 하나의 데이터 타입만 넣을 수 있음.<br>


In [2]:
test_array = np.array([1, 4, 5, 7], float)

In [3]:
test_array

array([ 1.,  4.,  5.,  7.])

In [5]:
type(test_array[3])

numpy.float64

In [11]:
test_array = np.array([1, 4, 6, "8"], np.float32)
test_array

#다이나믹 타이핑 -> 알아서 다 바꿔줌

array([ 1.,  4.,  6.,  8.], dtype=float32)

In [9]:
type(test_array[3])

numpy.float32

In [10]:
test_array.dtype

dtype('float32')

In [12]:
test_array.shape
# 4, 라고 있으면 4개의 메트릭스가 있는 백터

(4,)

In [14]:
test_array.ndim
#차원을 보여줌

1

In [15]:
test_array.size
#총 몇개인지를 보여줌

4

dtype

In [3]:
import numpy as np

## Handling Shape

### Reshape

In [4]:
test_matrix = [[1,2,3,4], [1,2,5,8]]

In [5]:
np.array(test_matrix).reshape(8, )

array([1, 2, 3, 4, 1, 2, 5, 8])

#### Flatten 
데이터를 1차원으로 펴줌. 


## Indexing and Slicing

In [6]:
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [8]:
test_exmaple[:,1:3] 
test_exmaple[1,:2]

array([1, 2])