In [2]:
import tensorflow as tf

In [3]:
hello = tf.constant('Hello, TensorFlow!')

In [4]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [5]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [8]:
sess = tf.Session()
print(sess.run(hello))
print(sess.run([a, b, c]))
sess.close()

b'Hello, TensorFlow!'
[10, 32, 42]


In [9]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [10]:
x_data = [[1, 2, 3], [4, 5, 6]]

In [12]:
x_data

[[1, 2, 3], [4, 5, 6]]

In [13]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

In [14]:
W

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32_ref>

In [15]:
W = tf.Variable([[0.1, 0.1], [0.2, 0.2], [0.3, 0.3]])

In [17]:
expr = tf.matmul(X, W) + b

In [18]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [20]:
print("====x_data======")
print(x_data)
print("====W======")
print(sess.run(W))
print("====b======")
print(sess.run(b))
print("====expr======")
print(sess.run(expr, feed_dict={X: x_data}))

====x_data======
[[1, 2, 3], [4, 5, 6]]
====W======
[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]
====b======
[[ 0.03963786]
 [-1.4354566 ]]
====expr======
[[1.4396379 1.4396379]
 [1.7645434 1.7645434]]


## Linear Regression

In [21]:
x_data = [1, 2, 3]
y_data = [1, 2, 3]

In [22]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

In [23]:
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

In [24]:
hypothesis = W*X + b 

In [25]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [27]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
training_op = optimizer.minimize(cost)

In [33]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([training_op, cost], feed_dict = {X: x_data, Y: y_data})
#         print([step, cost_val, sess.run(W), sess.run(b)])
    print("X: 5, Y:", sess.run(hypothesis, feed_dict = {X: 5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict = {X: 2.5}))

X: 5, Y: [5.003003]
X: 2.5, Y: [2.5002496]
